// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2023-03-07
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "baling-type" keywords (or names).
 *
 * Also used by: "baling-type-supported".
 *
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings30-20220527-5100.1.pdf">PWG5100.1-2022</a>
 */
public class BalingType {
    public static final String band = "band";
    public static final String shrinkWrap = "shrink-wrap";
    public static final String wrap = "wrap";
}