// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2023-11-27
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "coating-sides" keywords.
 *
 * Also used by: "coating-sides-supported".
 *
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippfinishings30-20220527-5100.1.pdf">PWG5100.1-2022</a>
 */
public class CoatingSides {
    public static final String back = "back";
    public static final String both = "both";
    public static final String front = "front";
}