// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2020-06-10
@file:Suppress("MaxLineLength", "WildcardImport")

package com.hp.jipp.model

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "input-scan-regions-supported" collection as defined in:
 * [PWG5100.15](https://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class InputScanRegionsSupported
constructor(
    var xDimension: IntRange? = null,
    var xOrigin: IntRange? = null,
    var yDimension: IntRange? = null,
    var yOrigin: IntRange? = null
) : AttributeCollection {

    /** Construct an empty [InputScanRegionsSupported]. */
    constructor() : this(null, null, null, null)

    /** Produce an attribute list from members. */
    override val attributes: List<Attribute<*>>
        get() = listOfNotNull(
            xDimension?.let { InputScanRegionsSupported.xDimension.of(it) },
            xOrigin?.let { InputScanRegionsSupported.xOrigin.of(it) },
            yDimension?.let { InputScanRegionsSupported.yDimension.of(it) },
            yOrigin?.let { InputScanRegionsSupported.yOrigin.of(it) }
        )

    /** Defines types for each member of [InputScanRegionsSupported]. */
    companion object : AttributeCollection.Converter<InputScanRegionsSupported> {
        override fun convert(attributes: List<Attribute<*>>): InputScanRegionsSupported =
            InputScanRegionsSupported(
                extractOne(attributes, xDimension),
                extractOne(attributes, xOrigin),
                extractOne(attributes, yDimension),
                extractOne(attributes, yOrigin)
            )
        override val cls = InputScanRegionsSupported::class.java
        @Deprecated("Remove this symbol")
        @JvmField val Types = this
        @JvmField val xDimension = IntRangeType("x-dimension")
        @JvmField val xOrigin = IntRangeType("x-origin")
        @JvmField val yDimension = IntRangeType("y-dimension")
        @JvmField val yOrigin = IntRangeType("y-origin")
    }
    override fun toString() = "InputScanRegionsSupported(${attributes.joinToString()})"
}
