// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2019-05-28
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "ipp-features-supported" keywords.
 *
 * @see <a href="https://www.pwg.org/pipermail/ipp/2016/018914.html">APPLE-ICC</a>
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf">PWG5100.13</a>
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippeve10-20130128-5100.14.pdf">PWG5100.14</a>
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf">PWG5100.15</a>
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippscan10-20140918-5100.17.pdf">PWG5100.17</a>
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf">PWG5100.18</a>
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d11-20190329-5100.21.pdf">PWG5100.21</a>
 */
public class IppFeaturesSupported {
    public static final String documentObject = "document-object";
    public static final String faxout = "faxout";
    public static final String iccColorMatching = "icc-color-matching";
    public static final String infrastructurePrinter = "infrastructure-printer";
    public static final String ipp3d = "ipp-3d";
    public static final String ippEverywhere = "ipp-everywhere";
    public static final String jobSave = "job-save";
    public static final String none = "none";
    public static final String pageOverrides = "page-overrides";
    public static final String proofPrint = "proof-print";
    public static final String scan = "scan";
    public static final String subscriptionObject = "subscription-object";
}