// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2023-03-07
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "job-destination-spooling-supported" keywords.
 *
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippscan10-20140918-5100.17.pdf">PWG5100.17</a>
 */
public class JobDestinationSpoolingSupported {
    public static final String automatic = "automatic";
    public static final String spool = "spool";
    public static final String stream = "stream";
}