// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2020-02-20
@file:Suppress("MaxLineLength", "WildcardImport")

package com.hp.jipp.model

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "job-error-sheet" collection as defined in:
 * [PWG5100.3](https://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class JobErrorSheet
constructor(
    /** May contain any keyword from [JobErrorSheetType] or a name. */
    var jobErrorSheetType: KeywordOrName? = null,
    /** May contain any keyword from [JobErrorSheetWhen]. */
    var jobErrorSheetWhen: String? = null,
    /** May contain any keyword from [Media] or a name. */
    var media: KeywordOrName? = null,
    var mediaCol: MediaCol? = null
) : AttributeCollection {

    /** Construct an empty [JobErrorSheet]. */
    constructor() : this(null, null, null, null)

    /** Produce an attribute list from members. */
    override val attributes: List<Attribute<*>> by lazy {
        listOfNotNull(
            jobErrorSheetType?.let { Types.jobErrorSheetType.of(it) },
            jobErrorSheetWhen?.let { Types.jobErrorSheetWhen.of(it) },
            media?.let { Types.media.of(it) },
            mediaCol?.let { Types.mediaCol.of(it) }
        )
    }

    /** Types for each member attribute. */
    object Types {
        @JvmField val jobErrorSheetType = KeywordOrNameType("job-error-sheet-type")
        @JvmField val jobErrorSheetWhen = KeywordType("job-error-sheet-when")
        @JvmField val media = KeywordOrNameType("media")
        @JvmField val mediaCol = AttributeCollection.Type("media-col", MediaCol)
    }

    /** Defines types for each member of [JobErrorSheet] */
    companion object : AttributeCollection.Converter<JobErrorSheet> {
        override fun convert(attributes: List<Attribute<*>>): JobErrorSheet =
            JobErrorSheet(
                extractOne(attributes, Types.jobErrorSheetType),
                extractOne(attributes, Types.jobErrorSheetWhen),
                extractOne(attributes, Types.media),
                extractOne(attributes, Types.mediaCol)
            )
    }
    override fun toString() = "JobErrorSheet(${attributes.joinToString()})"
}
