// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2022-08-02
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "label-mode-configured" keywords.
 *
 * Also used by: "label-mode-supported".
 *
 * @see <a href="https://ftp.pwg.org/pub/pwg/ipp/registrations/reg-ipplabel10-20200213.pdf">IPPLABEL</a>
 */
public class LabelModeConfigured {
    public static final String applicator = "applicator";
    public static final String cutter = "cutter";
    public static final String cutterDelayed = "cutter-delayed";
    public static final String kiosk = "kiosk";
    public static final String peelOff = "peel-off";
    public static final String peelOffPrepeel = "peel-off-prepeel";
    public static final String rewind = "rewind";
    public static final String rfid = "rfid";
    public static final String tearOff = "tear-off";
}