// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2020-06-10
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "media-tracking" keywords.
 *
 * Also used by: "media-tracking-supported".
 *
 * @see <a href="https://ftp.pwg.org/pub/pwg/ipp/registrations/reg-ipplabel10-20200213.pdf">IPPLABEL</a>
 */
public class MediaTracking {
    public static final String continuous = "continuous";
    public static final String mark = "mark";
    public static final String web = "web";
}