// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2023-11-27
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "media-tooth" keywords (or names).
 *
 * Also used by: "media-tooth-supported".
 *
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext21-20230210-5100.7.pdf">PWG5100.7</a>
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-pwgmsn20-20130328-5101.1.pdf">PWG5101.1-2013</a>
 */
public class MediaTooth {
    public static final String antique = "antique";
    public static final String calendared = "calendared";
    public static final String coarse = "coarse";
    public static final String fine = "fine";
    public static final String linen = "linen";
    public static final String medium = "medium";
    public static final String smooth = "smooth";
    public static final String stipple = "stipple";
    public static final String uncalendared = "uncalendared";
    public static final String vellum = "vellum";
}