// Copyright 2018 - 2025 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2025-05-13
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "print-supports" keywords.
 *
 * Also used by: "print-supports-actual", "print-supports-default", "print-supports-supported".
 *
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d11-20190329-5100.21.pdf">PWG5100.21</a>
 */
public class PrintSupports {
    public static final String material = "material";
    public static final String none = "none";
    public static final String standard = "standard";
}