// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength", "WildcardImport")

package com.hp.jipp.model

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "proof-print" collection as defined in:
 * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class ProofPrint
@JvmOverloads constructor(
    /** May contain any keyword from [Media] or a name. */
    var media: String? = null,
    var mediaCol: MediaCol? = null,
    var proofPrintCopies: Int? = null
) : AttributeCollection {

    /** Produce an attribute list from members. */
    override val attributes: List<Attribute<*>> by lazy {
        listOfNotNull(
            media?.let { Types.media.of(it) },
            mediaCol?.let { Types.mediaCol.of(it) },
            proofPrintCopies?.let { Types.proofPrintCopies.of(it) }
        )
    }

    /** Type for attributes of this collection */
    class Type(override val name: String) : AttributeCollection.Type<ProofPrint>(ProofPrint)

    /** All member names as strings. */
    object Name {
        /** "media" member name */
        const val media = "media"
        /** "media-col" member name */
        const val mediaCol = "media-col"
        /** "proof-print-copies" member name */
        const val proofPrintCopies = "proof-print-copies"
    }

    /** Types for each member attribute. */
    object Types {
        val media = KeywordType(Name.media)
        val mediaCol = MediaCol.Type(Name.mediaCol)
        val proofPrintCopies = IntType(Name.proofPrintCopies)
    }

    /** Defines types for each member of [ProofPrint] */
    companion object : AttributeCollection.Converter<ProofPrint> {
        override fun convert(attributes: List<Attribute<*>>): ProofPrint =
            ProofPrint(
                extractOne(attributes, Types.media),
                extractOne(attributes, Types.mediaCol),
                extractOne(attributes, Types.proofPrintCopies)
            )
    }
}
