// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2024-06-13
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "resource-type" keywords.
 *
 * @see <a href="https://ftp.pwg.org/pub/pwg/candidates/cs-ippsystem10-20191122-5100.22.pdf">PWG5100.22</a>
 */
public class ResourceType {
    public static final String executableFirmware = "executable-firmware";
    public static final String executableSoftware = "executable-software";
    public static final String staticFont = "static-font";
    public static final String staticForm = "static-form";
    public static final String staticIccProfile = "static-icc-profile";
    public static final String staticImage = "static-image";
    public static final String staticLogo = "static-logo";
    public static final String staticOther = "static-other";
    public static final String staticStrings = "static-strings";
    public static final String templateDocument = "template-document";
    public static final String templateJob = "template-job";
    public static final String templatePrinter = "template-printer";
}