// Copyright 2018 - 2024 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2024-06-13
//
// (Note: Uses Java, not Kotlin, to define public static values in the most efficient manner.)

package com.hp.jipp.model;

/**
 * Values applicable for "sides" keywords.
 *
 * Also used by: "input-sides", "input-sides-supported", "sides-default", "sides-supported".
 *
 * @see <a href="http://www.iana.org/go/rfc8011">RFC8011</a>
 */
public class Sides {
    public static final String oneSided = "one-sided";
    public static final String twoSidedLongEdge = "two-sided-long-edge";
    public static final String twoSidedShortEdge = "two-sided-short-edge";
}