// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength", "WildcardImport")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "destination-statuses" collection as defined in:
 * [PWG5100.15](http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class DestinationStatuses
@JvmOverloads constructor(
    val destinationUri: java.net.URI? = null,
    val imagesCompleted: Int? = null,
    val transmissionStatus: TransmissionStatus? = null,
    /** Original parameters received, if any. */
    val _original: List<Attribute<*>>? = null
) : AttributeCollection {

    /** Produce an attribute list from members, or return the [_original] attribute list (if it exists). */
    override val attributes: List<Attribute<*>> by lazy {
        _original ?: listOfNotNull(
            destinationUri?.let { Members.destinationUri.of(it) },
            imagesCompleted?.let { Members.imagesCompleted.of(it) },
            transmissionStatus?.let { Members.transmissionStatus.of(it) }
        )
    }

    /** Type for attributes of this collection */
    class Type(override val name: String) : AttributeCollection.Type<DestinationStatuses>(Members)

    /** All member names as strings. */
    object Name {
        /** "destination-uri" member name */
        const val destinationUri = "destination-uri"
        /** "images-completed" member name */
        const val imagesCompleted = "images-completed"
        /** "transmission-status" member name */
        const val transmissionStatus = "transmission-status"
    }

    companion object Members : AttributeCollection.Converter<DestinationStatuses> {
        override fun convert(attributes: List<Attribute<*>>): DestinationStatuses =
            DestinationStatuses(
                extractOne(attributes, destinationUri),
                extractOne(attributes, imagesCompleted),
                extractOne(attributes, transmissionStatus),
                _original = attributes)
        /**
         * "destination-uri" member type.
         */
        @JvmField val destinationUri = UriType(Name.destinationUri)
        /**
         * "images-completed" member type.
         */
        @JvmField val imagesCompleted = IntType(Name.imagesCompleted)
        /**
         * "transmission-status" member type.
         */
        @JvmField val transmissionStatus = TransmissionStatus.Type(Name.transmissionStatus)
    }
}
