// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06

package com.hp.jipp.pwg;

/**
 * Values applicable for "input-content-type" keywords, as defined in
 * <a href="http://ftp.pwg.org/pub/pwg/candidates/cs-ippfaxout10-20131115-5100.15.pdf">PWG5100.15</a>.
 *
 * Also used by:
 *   * `input-content-type-supported`
 */
public class InputContentType {
    public static final String auto = "auto";
    public static final String halftone = "halftone";
    public static final String lineArt = "line-art";
    public static final String magazine = "magazine";
    public static final String photo = "photo";
    public static final String text = "text";
    public static final String textAndPhoto = "text-and-photo";
}