// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength", "WildcardImport")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "insert-sheet" collection as defined in:
 * [PWG5100.3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf),
 * [RFC8011](http://www.iana.org/go/rfc8011).
 */
@Suppress("RedundantCompanionReference", "unused")
data class InsertSheet
@JvmOverloads constructor(
    val insertAfterPageNumber: Int? = null,
    val insertCount: Int? = null,
    /** May contain any keyword from [Media] or a name. */
    val media: String? = null,
    val mediaCol: MediaCol? = null,
    /** Encoded form, if known. */
    val _encoded: List<Attribute<*>>? = null
) : AttributeCollection {

    /** Produce an attribute list from members, or return the original [_encoded] attribute list if present. */
    override val attributes: List<Attribute<*>> by lazy {
        _encoded ?: listOfNotNull(
            insertAfterPageNumber?.let { Members.insertAfterPageNumber.of(it) },
            insertCount?.let { Members.insertCount.of(it) },
            media?.let { Members.media.of(it) },
            mediaCol?.let { Members.mediaCol.of(it) }
        )
    }

    /** Type for attributes of this collection */
    class Type(override val name: String) : AttributeCollection.Type<InsertSheet>(Members)

    /** All member names as strings. */
    object Name {
        /** "insert-after-page-number" member name */
        const val insertAfterPageNumber = "insert-after-page-number"
        /** "insert-count" member name */
        const val insertCount = "insert-count"
        /** "media" member name */
        const val media = "media"
        /** "media-col" member name */
        const val mediaCol = "media-col"
    }

    /** Builder for immutable [InsertSheet] objects. */
    class Builder() {
        /** Constructs a new [Builder] pre-initialized with values in [source]. */
        constructor(source: InsertSheet) : this() {
            insertAfterPageNumber = source.insertAfterPageNumber
            insertCount = source.insertCount
            media = source.media
            mediaCol = source.mediaCol
        }
        var insertAfterPageNumber: Int? = null
        var insertCount: Int? = null
        /** May contain any keyword from [Media] or a name. */
        var media: String? = null
        var mediaCol: MediaCol? = null

        /** Return a new [InsertSheet] object containing all values initialized in this builder. */
        fun build() = InsertSheet(
            insertAfterPageNumber,
            insertCount,
            media,
            mediaCol
        )
    }

    companion object Members : AttributeCollection.Converter<InsertSheet> {
        override fun convert(attributes: List<Attribute<*>>): InsertSheet =
            InsertSheet(
                extractOne(attributes, insertAfterPageNumber),
                extractOne(attributes, insertCount),
                extractOne(attributes, media),
                extractOne(attributes, mediaCol),
                _encoded = attributes)
        /**
         * "insert-after-page-number" member type.
         */
        @JvmField val insertAfterPageNumber = IntType(Name.insertAfterPageNumber)
        /**
         * "insert-count" member type.
         */
        @JvmField val insertCount = IntType(Name.insertCount)
        /**
         * "media" member type.
         * May contain any keyword from [Media] or a name.
         */
        @JvmField val media = KeywordType(Name.media)
        /**
         * "media-col" member type.
         */
        @JvmField val mediaCol = MediaCol.Type(Name.mediaCol)
    }
}
