// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06

package com.hp.jipp.pwg;

/**
 * Values applicable for "jpeg-features-supported" keywords, as defined in
 * <a href="http://www.pwg.org/pipermail/ipp/2015/018634.html">APPLE20151021</a>.
 */
public class JpegFeaturesSupported {
    public static final String arithmetic = "arithmetic";
    public static final String cmyk = "cmyk";
    public static final String deep = "deep";
    public static final String hierarchical = "hierarchical";
    public static final String icc = "icc";
    public static final String lossless = "lossless";
    public static final String none = "none";
    public static final String progressive = "progressive";
}