// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06

package com.hp.jipp.pwg;

/**
 * Values applicable for "media-back-coating" keywords (or names), as defined in
 * <a href="http://ftp.pwg.org/pub/pwg/candidates/cs-ippprodprint10-20010212-5100.3.pdf">PWG5100.3</a>.
 *
 * Also used by:
 *   * `media-back-coating-supported`
 *   * `media-front-coating`
 *   * `media-front-coating-supported`
 */
public class MediaBackCoating {
    public static final String glossy = "glossy";
    public static final String highGloss = "high-gloss";
    public static final String matte = "matte";
    public static final String none = "none";
    public static final String satin = "satin";
    public static final String semiGloss = "semi-gloss";
}