// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06

package com.hp.jipp.pwg;

/**
 * Values applicable for "multiple-operation-time-out-action" keywords, as defined in
 * <a href="http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf">PWG5100.13</a>.
 */
public class MultipleOperationTimeOutAction {
    public static final String abortJob = "abort-job";
    public static final String holdJob = "hold-job";
    public static final String processJob = "process-job";
}