// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06

package com.hp.jipp.pwg;

/**
 * Values applicable for "notify-events" keywords, as defined in
 * <a href="http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf">PWG5100.18</a>,
 * <a href="http://www.iana.org/go/rfc3995">RFC3995</a>.
 *
 * Also used by:
 *   * `notify-events-default`
 *   * `notify-events-supported`
 *   * `notify-subscribed-event`
 */
public class NotifyEvent {
    public static final String documentCompleted = "document-completed";
    public static final String documentConfigChanged = "document-config-changed";
    public static final String documentCreated = "document-created";
    public static final String documentFetchable = "document-fetchable";
    public static final String documentStateChanged = "document-state-changed";
    public static final String documentStopped = "document-stopped";
    public static final String jobCompleted = "job-completed";
    public static final String jobConfigChanged = "job-config-changed";
    public static final String jobCreated = "job-created";
    public static final String jobFetchable = "job-fetchable";
    public static final String jobProgress = "job-progress";
    public static final String jobStateChanged = "job-state-changed";
    public static final String jobStopped = "job-stopped";
    public static final String none = "none";
    public static final String printerConfigChanged = "printer-config-changed";
    public static final String printerFinishingsChanged = "printer-finishings-changed";
    public static final String printerMediaChanged = "printer-media-changed";
    public static final String printerQueueOrderChanged = "printer-queue-order-changed";
    public static final String printerRestarted = "printer-restarted";
    public static final String printerShutdown = "printer-shutdown";
    public static final String printerStateChanged = "printer-state-changed";
    public static final String printerStopped = "printer-stopped";
}