// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength", "WildcardImport")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "printer-volume-supported" collection as defined in:
 * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class PrinterVolumeSupported
@JvmOverloads constructor(
    val xDimension: Int? = null,
    val yDimension: Int? = null,
    val zDimension: Int? = null,
    /** Original parameters received, if any. */
    val _original: List<Attribute<*>>? = null
) : AttributeCollection {

    /** Produce an attribute list from members, or return the [_original] attribute list (if it exists). */
    override val attributes: List<Attribute<*>> by lazy {
        _original ?: listOfNotNull(
            xDimension?.let { Members.xDimension.of(it) },
            yDimension?.let { Members.yDimension.of(it) },
            zDimension?.let { Members.zDimension.of(it) }
        )
    }

    /** Type for attributes of this collection */
    class Type(override val name: String) : AttributeCollection.Type<PrinterVolumeSupported>(Members)

    /** All member names as strings. */
    object Name {
        /** "x-dimension" member name */
        const val xDimension = "x-dimension"
        /** "y-dimension" member name */
        const val yDimension = "y-dimension"
        /** "z-dimension" member name */
        const val zDimension = "z-dimension"
    }

    companion object Members : AttributeCollection.Converter<PrinterVolumeSupported> {
        override fun convert(attributes: List<Attribute<*>>): PrinterVolumeSupported =
            PrinterVolumeSupported(
                extractOne(attributes, xDimension),
                extractOne(attributes, yDimension),
                extractOne(attributes, zDimension),
                _original = attributes)
        /**
         * "x-dimension" member type.
         */
        @JvmField val xDimension = IntType(Name.xDimension)
        /**
         * "y-dimension" member type.
         */
        @JvmField val yDimension = IntType(Name.yDimension)
        /**
         * "z-dimension" member type.
         */
        @JvmField val zDimension = IntType(Name.zDimension)
    }
}
