// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength", "WildcardImport")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "print-accuracy" collection as defined in:
 * [PWG5100.21](http://ftp.pwg.org/pub/pwg/candidates/cs-ipp3d10-20170210-5100.21.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class PrintAccuracy
@JvmOverloads constructor(
    /** May contain any keyword from [AccuracyUnit]. */
    val accuracyUnits: String? = null,
    val xAccuracy: Int? = null,
    val yAccuracy: Int? = null,
    val zAccuracy: Int? = null,
    /** Encoded form, if known. */
    val _encoded: List<Attribute<*>>? = null
) : AttributeCollection {

    /** Produce an attribute list from members, or return the original [_encoded] attribute list if present. */
    override val attributes: List<Attribute<*>> by lazy {
        _encoded ?: listOfNotNull(
            accuracyUnits?.let { Members.accuracyUnits.of(it) },
            xAccuracy?.let { Members.xAccuracy.of(it) },
            yAccuracy?.let { Members.yAccuracy.of(it) },
            zAccuracy?.let { Members.zAccuracy.of(it) }
        )
    }

    /** Type for attributes of this collection */
    class Type(override val name: String) : AttributeCollection.Type<PrintAccuracy>(Members)

    /** All member names as strings. */
    object Name {
        /** "accuracy-units" member name */
        const val accuracyUnits = "accuracy-units"
        /** "x-accuracy" member name */
        const val xAccuracy = "x-accuracy"
        /** "y-accuracy" member name */
        const val yAccuracy = "y-accuracy"
        /** "z-accuracy" member name */
        const val zAccuracy = "z-accuracy"
    }

    /** Builder for immutable [PrintAccuracy] objects. */
    class Builder() {
        /** Constructs a new [Builder] pre-initialized with values in [source]. */
        constructor(source: PrintAccuracy) : this() {
            accuracyUnits = source.accuracyUnits
            xAccuracy = source.xAccuracy
            yAccuracy = source.yAccuracy
            zAccuracy = source.zAccuracy
        }
        /** May contain any keyword from [AccuracyUnit]. */
        var accuracyUnits: String? = null
        var xAccuracy: Int? = null
        var yAccuracy: Int? = null
        var zAccuracy: Int? = null

        /** Return a new [PrintAccuracy] object containing all values initialized in this builder. */
        fun build() = PrintAccuracy(
            accuracyUnits,
            xAccuracy,
            yAccuracy,
            zAccuracy
        )
    }

    companion object Members : AttributeCollection.Converter<PrintAccuracy> {
        override fun convert(attributes: List<Attribute<*>>): PrintAccuracy =
            PrintAccuracy(
                extractOne(attributes, accuracyUnits),
                extractOne(attributes, xAccuracy),
                extractOne(attributes, yAccuracy),
                extractOne(attributes, zAccuracy),
                _encoded = attributes)
        /**
         * "accuracy-units" member type.
         * May contain any keyword from [AccuracyUnit].
         */
        @JvmField val accuracyUnits = KeywordType(Name.accuracyUnits)
        /**
         * "x-accuracy" member type.
         */
        @JvmField val xAccuracy = IntType(Name.xAccuracy)
        /**
         * "y-accuracy" member type.
         */
        @JvmField val yAccuracy = IntType(Name.yAccuracy)
        /**
         * "z-accuracy" member type.
         */
        @JvmField val zAccuracy = IntType(Name.zAccuracy)
    }
}
