// Copyright 2018 HP Development Company, L.P.
// SPDX-License-Identifier: MIT
//
// DO NOT MODIFY. Code is auto-generated by genTypes.py. Content taken from registry at
// https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml, updated on 2018-04-06
@file:Suppress("MaxLineLength", "WildcardImport")

package com.hp.jipp.pwg

import com.hp.jipp.encoding.* // ktlint-disable no-wildcard-imports

/**
 * Data object corresponding to a "proof-print" collection as defined in:
 * [PWG5100.11](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext10-20101030-5100.11.pdf).
 */
@Suppress("RedundantCompanionReference", "unused")
data class ProofPrint
@JvmOverloads constructor(
    /** May contain any keyword from [Media] or a name. */
    val media: String? = null,
    val mediaCol: MediaCol? = null,
    val proofPrintCopies: Int? = null,
    /** Encoded form, if known. */
    val _encoded: List<Attribute<*>>? = null
) : AttributeCollection {

    /** Produce an attribute list from members, or return the original [_encoded] attribute list if present. */
    override val attributes: List<Attribute<*>> by lazy {
        _encoded ?: listOfNotNull(
            media?.let { Members.media.of(it) },
            mediaCol?.let { Members.mediaCol.of(it) },
            proofPrintCopies?.let { Members.proofPrintCopies.of(it) }
        )
    }

    /** Type for attributes of this collection */
    class Type(override val name: String) : AttributeCollection.Type<ProofPrint>(Members)

    /** All member names as strings. */
    object Name {
        /** "media" member name */
        const val media = "media"
        /** "media-col" member name */
        const val mediaCol = "media-col"
        /** "proof-print-copies" member name */
        const val proofPrintCopies = "proof-print-copies"
    }

    /** Builder for immutable [ProofPrint] objects. */
    class Builder() {
        /** Constructs a new [Builder] pre-initialized with values in [source]. */
        constructor(source: ProofPrint) : this() {
            media = source.media
            mediaCol = source.mediaCol
            proofPrintCopies = source.proofPrintCopies
        }
        /** May contain any keyword from [Media] or a name. */
        var media: String? = null
        var mediaCol: MediaCol? = null
        var proofPrintCopies: Int? = null

        /** Return a new [ProofPrint] object containing all values initialized in this builder. */
        fun build() = ProofPrint(
            media,
            mediaCol,
            proofPrintCopies
        )
    }

    companion object Members : AttributeCollection.Converter<ProofPrint> {
        override fun convert(attributes: List<Attribute<*>>): ProofPrint =
            ProofPrint(
                extractOne(attributes, media),
                extractOne(attributes, mediaCol),
                extractOne(attributes, proofPrintCopies),
                _encoded = attributes)
        /**
         * "media" member type.
         * May contain any keyword from [Media] or a name.
         */
        @JvmField val media = KeywordType(Name.media)
        /**
         * "media-col" member type.
         */
        @JvmField val mediaCol = MediaCol.Type(Name.mediaCol)
        /**
         * "proof-print-copies" member type.
         */
        @JvmField val proofPrintCopies = IntType(Name.proofPrintCopies)
    }
}
